development:
  adapter: mysql
  encoding: utf8
  database: photobagel_development
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: photobagel_production
  username: root
  password:
  host: localhost