development:
  type: imap
  server: imap.gmail.com
  port: 993
  use_login: true
  processed_folder: imported
  ssl: true
  username: photobagel@gmail.com
  password: Jose897}Moor
  
production:
  type: imap
  server: imap.gmail.com
  port: 993
  use_login: true
  processed_folder: imported
  ssl: true
  username: photobagel@gmail.com
  password: Jose897}Moor